app/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"username"}, message="Ce nom d'utilisateur est déjà utilisé")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{

    private $plainPassword;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateRenewal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FirstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $LastName;

    /**
     * @ORM\ManyToMany(targetEntity=Article::class, inversedBy="users")
     */
    private $article;

    /**
     * @ORM\Column(type="array")
     */
    private $cart = [];

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="user", orphanRemoval=true)
     */
    private $reservations;
    /** 
     * @ORM\Column(type="string", length=255)
     */
    private $ImageName;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $birthDate;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Gender;

    public function __construct()
    {
        $this->article = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        $this->plainPassword = null;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getDateRenewal(): ?\DateTimeInterface
    {
        return $this->dateRenewal;
    }

    public function setDateRenewal(?\DateTimeInterface $dateRenewal): self
    {
        $this->dateRenewal = $dateRenewal;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function setPlainPassword(string $plainPassword)
    {
        $this->plainPassword = $plainPassword;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }


    public function getCart(): ?array
    {
        return $this->cart;
    }

    public function setCart(array $cart): self
    {
        $this->cart = $cart;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setUser($this);
        }
    }

    public function getImageName(): ?string
    {
        return $this->ImageName;
    }

    public function setImageName(string $ImageName): self
    {
        $this->ImageName = $ImageName;

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getUser() === $this) {
                $reservation->setUser(null);
            }
        }
    }
        
    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getBirthDate(): ?string
    {
        return $this->birthDate;
    }

    public function setBirthDate(string $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->Gender;
    }

    public function setGender(string $Gender): self
    {
        $this->Gender = $Gender;

        return $this;
    }
}

app/src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\ViewLog  ;
use App\Form\VerifMdpType;
use App\Form\ProfileType;
use App\Form\ChangeAddressType;
use App\Form\ChangeTelephoneType;
use App\Form\ChangeImageType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;


#[Route('/profil')]
class ProfileController extends AbstractController
{
    private function registerVisit(EntityManagerInterface $entityManager)
    {
        $viewLog = new ViewLog();
        $viewLog->setDate(new \DateTime("now", new \DateTimeZone("Europe/Paris")));
        $entityManager->persist($viewLog);
        $entityManager->flush();
    }

    #[Route('/', name: 'profile', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $this->registerVisit($entityManager);

        return $this->render('profile/index.html.twig', [
            'controller_name' => 'ProfileController',
            'user' => $this->getUser(),
        ]);
    }


    #[Route('/verifMail', name: 'verif_mail', methods: ['GET','POST'])]
    public function verifMail(EntityManagerInterface $em, Request $request, UserPasswordHasherInterface $passwordHasher, ValidatorInterface $validator): Response
    {
        $user = $this->getUser();
        $entity = $em->getRepository(User::class)->findOneBy(['username' => $user->getUserIdentifier()]);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $form = $this->createForm(ProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userData = $form->getData();
            if ($userData->getPlainPassword() !== null) {
                $userData->setPassword($passwordHasher->hashPassword(
                    $userData,
                    $userData->getPlainPassword(),
                )
                );
            }
            $em->flush();
            return $this->redirectToRoute('profile', [], Response::HTTP_SEE_OTHER);
        }

        $em->refresh($user);

        return $this->render('profile/edit.html.twig', [
            'controller_name' => 'ProfileController',
            'form' => $form->createView(),
        ]);
    }


    #[Route('/changeAddress', name: 'change_address', methods: ['GET','POST'])]
    public function changeAddress(EntityManagerInterface $em, Request $request, UserPasswordHasherInterface $passwordHasher, ValidatorInterface $validator): Response
    {
        $user = $this->getUser();
        $entity = $em->getRepository(User::class)->findOneBy(['username' => $user->getUserIdentifier()]);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $form = $this->createForm(ChangeAddressType::class, $user);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em->flush();
            return $this->redirectToRoute('profile', [], Response::HTTP_SEE_OTHER);
        }

        $em->refresh($user);

        return $this->render('profile/editAddress.html.twig', [
            'controller_name' => 'ProfileController',
            'form' => $form->createView(),
        ]);
    }

    #[Route('/changeTelephone', name: 'change_telephone', methods: ['GET','POST'])]
    public function changeTelephone(EntityManagerInterface $em, Request $request, UserPasswordHasherInterface $passwordHasher, ValidatorInterface $validator): Response
    {
        $user = $this->getUser();
        $entity = $em->getRepository(User::class)->findOneBy(['username' => $user->getUserIdentifier()]);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $form = $this->createForm(ChangeTelephoneType::class, $user);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em->flush();
            return $this->redirectToRoute('profile', [], Response::HTTP_SEE_OTHER);
        }

        $em->refresh($user);

        return $this->render('profile/editTelephone.html.twig', [
            'controller_name' => 'ProfileController',
            'form' => $form->createView(),
        ]);
    }


    #[Route('/changeImage', name: 'change_image', methods: ['GET','POST'])]
    public function changeImage(EntityManagerInterface $em, Request $request, UserPasswordHasherInterface $passwordHasher, ValidatorInterface $validator): Response
    {
        $user = $this->getUser();
        $entity = $em->getRepository(User::class)->findOneBy(['username' => $user->getUserIdentifier()]);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $form = $this->createForm(ChangeImageType::class, $user);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if($user->getImageName() != null){
                $filesystem = new Filesystem();
                $filesystem->remove("ImageProfil/" .$user->getImageName());
            }


            $image = $form->get("image")->getData();

            if ($image != null){
                $name = md5(uniqid()).'.'.$image->guessExtension();
                $image->move('ImageProfil', $name);

                $user->setImageName($name);
            }

            $em->flush();
            return $this->redirectToRoute('profile', [], Response::HTTP_SEE_OTHER);
        }

        $em->refresh($user);

        return $this->render('profile/editImage.html.twig', [
            'controller_name' => 'ProfileController',
            'form' => $form->createView(),
        ]);
    }

    #[Route('/verifMdp', name: 'verif_mdp', methods: ['GET','POST'])]
    public function verifMdp(EntityManagerInterface $em, Request $request, UserPasswordHasherInterface $passwordHasher, ValidatorInterface $validator, MailerInterface $mailer): Response
    {
        $user = $this->getUser();
        $entity = $em->getRepository(User::class)->findOneBy(['username' => $user->getUserIdentifier()]);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $oldMail = $user->getMail();
        $form = $this->createForm(VerifMdpType::class, [$user, $passwordHasher]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userData = $form->getData();
            if ($userData["mail"] !== null) {
                $newMail = $userData["mail"];
                $user->setMail($userData["mail"]);

                $email1 = (new TemplatedEmail())
                    ->from('support@asso-prefecture.com')
                    ->to($newMail)
                    ->subject('Changement d\'adresse-mail de votre comptre sur le site de l\'association de la préfecture de Haute Vienne')

                    ->htmlTemplate('mailer/MailEditMailNewAddress.html.twig')
                    ->context([
                        'firstname' => $user->getFirstname(),
                        'lastname' => $user->getLastname(),
                        'oldMail' => $oldMail,
                    ]);
                $mailer->send($email1);

                $email2 = (new TemplatedEmail())
                    ->from('support@asso-prefecture.com')
                    ->to($oldMail)
                    ->subject('Changement d\'adresse-mail de votre comptre sur le site de l\'association de la préfecture de Haute Vienne')

                    ->htmlTemplate('mailer/MailEditMailOldAddress.html.twig')
                    ->context([
                        'firstname' => $user->getFirstname(),
                        'lastname' => $user->getLastname(),
                        'newMail' =>$newMail,
                    ]);
                $mailer->send($email2);
            }
            $em->flush();
            return $this->redirectToRoute('profile', [], Response::HTTP_SEE_OTHER);
        }

        $em->refresh($user);

        return $this->render('profile/editPassword.html.twig', [
            'controller_name' => 'ProfileController',
            'form' => $form->createView(),
        ]);
    }


    #[Route('/edit', name: 'profile_edit', methods: ['GET','POST'])]
    public function edit(EntityManagerInterface $em, Request $request, UserPasswordHasherInterface $passwordHasher): Response
    {
        $user = $this->getUser();
        $entity = $em->getRepository(User::class)->findOneBy(['username' => $user->getUserIdentifier()]);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $form = $this->createForm(ProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userData = $form->getData();
            if ($userData->getPlainPassword() !== null) {
                $userData->setPassword($passwordHasher->hashPassword(
                    $userData,
                    $userData->getPlainPassword(),
                )
                );
            }

            $em->flush();

            return $this->redirectToRoute('profile', [], Response::HTTP_SEE_OTHER);
        }

        $em->refresh($user);

        return $this->render('profile/edit.html.twig', [
            'controller_name' => 'ProfileController',
            'form' => $form->createView(),
        ]);
    }
}

app/templates/profile/_form.html.twig
{% form_theme form 'tailwind_2_layout.html.twig' %}

{{ form_start(form) }}
    <div class="flex flex-col"> 
        
        {{ form_row(form.mail, {
            row_class: 'mt-2',
            label_class: 'font-medium block',
            error_item_class: 'text-red-700 ',
            widget_class: 'mb-2 p-2 border rounded-md border-black bg-white focus:bg-gray-200 transition hover:bg-gray-100 w-full',
            widget_disabled_class: 'border-dashed text-gray-200 ',
            widget_errors_class: 'border-double border-red-500 bg-red-50',
        }) }}

        {{ form_label(form.plainPassword.first, 'Mot de passe', { 'label_attr': {'class': 'font-medium block'} }) }}
        {{ form_widget(form.plainPassword.first, {'attr': {'class': 'mb-2 p-2 border rounded-md border-black bg-white focus:bg-gray-200 transition hover:bg-gray-100 w-full'}}) }}
        {{ form_label(form.plainPassword.second, 'Confirmer mot de passe', { 'label_attr': {'class': 'font-medium block'} }) }}
        {{ form_widget(form.plainPassword.second, {'attr': {'class': 'mb-2 p-2 border rounded-md border-black bg-white focus:bg-gray-200 transition hover:bg-gray-100 w-full'}}) }}

        <button class="self-center btn btn-lg btn-primary text-white font-bold box-content my-8 h-5 w-48 p-4 border-2 border-[#374779] transition text-white bg-[#374779] hover:bg-[#CBD8E5] hover:text-[#374779]">{{ button_label|default('Save') }}</button>
    </div>
{{ form_end(form) }}

app/templates/profile/_formChangeAddress.html.twig
{% form_theme form 'tailwind_2_layout.html.twig' %}

{{ form_start(form) }}
<div class="flex flex-col">

    {{ form_row(form.address, {
        row_class: 'mt-2',
        label_class: 'font-medium block',
        error_item_class: 'text-red-700 ',
        widget_class: 'mb-2 p-2 border rounded-md border-black bg-white focus:bg-gray-200 transition hover:bg-gray-100 w-full',
        widget_disabled_class: 'border-dashed text-gray-200 ',
        widget_errors_class: 'border-double border-red-500 bg-red-50',
    }) }}


    <button class="self-center btn btn-lg btn-primary text-white font-bold box-content my-8 h-5 w-48 p-4 border-2 border-[#374779] transition text-white bg-[#374779] hover:bg-[#CBD8E5] hover:text-[#374779]">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

app/templates/profile/_formChangeImage.html.twig
{% form_theme form 'tailwind_2_layout.html.twig' %}

{{ form_start(form) }}
<div class="flex flex-col">


    {{ form_row(form.image, {
        row_class: 'mt-2',
        label_class: 'font-medium block',
        error_item_class: 'text-red-700 ',
        widget_class: 'mb-2 p-2 border rounded-md border-black bg-white focus:bg-gray-200 transition hover:bg-gray-100 w-full',
        widget_disabled_class: 'border-dashed text-gray-200 ',
        widget_errors_class: 'border-double border-red-500 bg-red-50',
    }) }}

    <button class="self-center btn btn-lg btn-primary text-white font-bold box-content my-8 h-5 w-48 p-4 border-2 border-[#374779] transition text-white bg-[#374779] hover:bg-[#CBD8E5] hover:text-[#374779]">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

app/templates/profile/_formChangeTelephone.html.twig
{% form_theme form 'tailwind_2_layout.html.twig' %}

{{ form_start(form) }}
<div class="flex flex-col">

    {{ form_row(form.telephone, {
        row_class: 'mt-2',
        label_class: 'font-medium block',
        error_item_class: 'text-red-700 ',
        widget_class: 'mb-2 p-2 border rounded-md border-black bg-white focus:bg-gray-200 transition hover:bg-gray-100 w-full',
        widget_disabled_class: 'border-dashed text-gray-200 ',
        widget_errors_class: 'border-double border-red-500 bg-red-50',
    }) }}


    <button class="self-center btn btn-lg btn-primary text-white font-bold box-content my-8 h-5 w-48 p-4 border-2 border-[#374779] transition text-white bg-[#374779] hover:bg-[#CBD8E5] hover:text-[#374779]">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

app/templates/profile/_formEditPassword.html.twig
{% form_theme form 'tailwind_2_layout.html.twig' %}

{{ form_start(form) }}
<div class="flex flex-col">

    {{ form_row(form.plainPassword, {
        row_class: 'mt-2',
        label_class: 'font-medium block',
        error_item_class: 'text-red-700 ',
        widget_class: 'mb-2 p-2 border rounded-md border-black bg-white focus:bg-gray-200 transition hover:bg-gray-100 w-full',
        widget_disabled_class: 'border-dashed text-gray-200 ',
        widget_errors_class: 'border-double border-red-500 bg-red-50',
    }) }}

    {{ form_label(form.mail.first, 'Nouveau Mail', { 'label_attr': {'class': 'font-medium block'} }) }}
    {{ form_widget(form.mail.first, {'attr': {'class': 'mb-2 p-2 border rounded-md border-black bg-white focus:bg-gray-200 transition hover:bg-gray-100 w-full'}}) }}
    {{ form_label(form.mail.second, 'Confirmer Mail', { 'label_attr': {'class': 'font-medium block'} }) }}
    {{ form_widget(form.mail.second, {'attr': {'class': 'mb-2 p-2 border rounded-md border-black bg-white focus:bg-gray-200 transition hover:bg-gray-100 w-full'}}) }}

    <button class="self-center btn btn-lg btn-primary text-white font-bold box-content my-8 h-5 w-48 p-4 border-2 border-[#374779] transition text-white bg-[#374779] hover:bg-[#CBD8E5] hover:text-[#374779]">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

app/templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Association de la préfecture de la Haute-Vienne{% endblock %}

{% block body %}
    <div class="flex flex-col justify-evenly w-[40rem] h-fit px-32 m-auto my-8 rounded-lg shadow-md bg-gray-100">
        <h1 class="self-center text-4xl font-bold my-8">Modifier Profil</h1>

        {{ 
            include('profile/_form.html.twig', {'button_label': 'MODIFIER'}) 
        }}

        <a href="{{ path('profile') }}" class="self-center transition underline hover:text-blue-900 my-8">Retourner au profil</a>
    </div>
{% endblock %}

app/templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Association de la préfecture de la Haute-Vienne{% endblock %}

{% block body %}

    {% set fullName = "#{user.FirstName} #{user.LastName}" %}


    {# class="flex flex-col justify-evenly w-[40rem] h-fit px-32 m-auto my-8 rounded-lg shadow-md bg-gray-100"> #}
    <div class="flex flex-col justify-evenly h-fit overflow-hidden w-[65rem] m-auto my-8 rounded-lg shadow-md bg-gray-100 pb-4">

        <div class="overflow-hidden">
            <div class="align-start blur w-[65rem]">
                <img src="{{ asset('/ImageProfil/imageBackgroundProfile.png') }}"  alt="backgroundProfil">
            </div>
        </div>


        <div class="w-28 h-28 -mt-14 z-50 mx-auto border border-gray-100 border-4 rounded-full relative">
            {% if user.imageName is null %}
                <img class="rounded-full" src="{{ asset('/ImageProfil/profil_default.png')}}"  alt="imageProfil">
            {% else %}
                <img class="rounded-full" src="{{ asset('/ImageProfil/'~user.imageName)}}"  alt="imageProfil">
            {% endif %}
            <a  href="{{ path('change_image')}}"><span class="bg-white text-lg h-[2.5rem] text-center leading-[2.25em] transition hover:scale-125 w-[2.5rem] rounded-full absolute -top-[.5rem] -right-[.5rem]">✏️</span></a>
        </div>

        <div class="pb-5">
            <h1 class="font-bold text-xl text-center">{{ fullName }}</h1>
            <p class="text-xl text-center">{{ user.username }}</p>
        </div>


        <div class="flex flex-row flex-wrap justify-center px-28">
            <div class="basis-1/2 border-r-4 border-gray-300 pr-4">
                <h1 class="font-bold text-2xl text-center mb-3">Informations générales</h1>
                <table class="border border-gray-300 bg-white">
                    <tr class=" border border-gray-300">
                        <th class="p-4 w-[40%]">Nom et prénom</th>
                        <td class="p-4 w-[60%]">{{ fullName }}</td>
                    </tr>
                    <tr class="border border-gray-300">
                        <th class="p-4 w-[40%]" >Mail</th>
                        {% set lengthArobaseSplit = user.mail|split('@') %}
                        {% set lengthMail1 = lengthArobaseSplit[0]|length %}
                        {% set lengthMail2 = lengthArobaseSplit[1]|length %}
                        {% set nvMail = user.mail|slice(0, 3) %}

                        {% for i in 3..lengthMail1-1 %}
                            {% set nvMail = nvMail ~ '*' %}
                        {% endfor %}

                        {% set nvMail = nvMail ~ '@' %}

                        {% for i in 0..lengthMail2-1 %}
                            {% set nvMail = nvMail ~ '*' %}
                        {% endfor %}

                        <td class="p-4 w-[60%]">{{ nvMail }}</td>
                        <td><a class="text-xl" href="{{ path('verif_mdp')}}">✏</a></td>
                    </tr>
                    <tr class=" border border-gray-300">
                        <th class="p-4 w-[40%]">Mot de passe</th>
                        <td class="p-4 w-[60%] "><a class="text-navbar-background font-semibold underline" href="{{ path('app_forgot_password_request')}}">Changer le mot de passe</a></td>
                    </tr>

                </table>
            </div>

            <div class="basis-1/2 pl-4">
                <h1 class="font-bold text-2xl  text-center mb-3">Informations complémentaires</h1>
                <table class="border border-gray-300 bg-white">
                    <tr class="border border-gray-300">
                        <th class="p-4 w-[40%]" >Téléphone</th>
                        <td class="p-4 w-[60%]">{{ user.telephone }}</td>
                        <td><a class="text-xl" href="{{ path('change_telephone')}}">✏</a></td>
                    </tr>
                    <tr class="border border-gray-300">
                        <th class="p-4 w-[40%]">Adresse</th>
                        <td class="p-4 w-[60%]">{{ user.address }}</td>
                        <td><a class="text-xl" href="{{ path('change_address')}}">✏</a></td>
                    </tr>
                    <tr class="border border-gray-300">
                        <th class="p-4 w-[40%]">Date de naissance</th>
                        <td class="p-4 w-[60%]">{{ user.birthDate }}</td>
                    </tr>
                </table>
            </div>

            <div class="basis-1/2 py-5">
                <h1 class="font-bold text-2xl text-center mb-3">Autres</h1>
                <table class="border border-gray-300 bg-white">
                    <tr class="border border-gray-300">
                        <th class="p-4 w-[50%]" >Sexe</th>
                        <td class="p-4 w-[50%]">{{ user.gender }}</td>
                    </tr>
                    {% if user.roles|filter(role => role == "ROLE_ADHERENT")|first %}
                        <tr class="border group border-gray-300">
                            <th class="p-4 w-[50%]">Status d'adhésion</th>
                            <td class="p-4 w-[50%]">Adhérent</td>
                        </tr>
                        <tr class="border border-gray-300">
                            <th class="p-4 w-[50%]">Date de renouvellement</th>
                            {% set date = 'now'|date('d-m-Y') %}
                            {% set dateSplit = date|split('-') %}
                            {% set day = dateSplit[0] %}
                            {% set month = dateSplit[1] %}
                            {% set year = dateSplit[2] +1 %}
                            <td class="p-4 w-[50%]">{{ day }}-{{ month }}-{{ year }}</td>
                        </tr>
                    {% else %}
                        <tr class="border group border-gray-300">
                            <th class="p-4 w-[50%]">Status d'adhésion</th>
                            <td class="p-4 w-[50%]">Non adhérent</td>
                        </tr>
                        <tr class="border border-gray-300">
                            <th class="p-4 w-[50%]">Date de renouvellement</th>
                            <td class="p-4 w-[50%]">Pas de date prévue</td>
                        </tr>
                    {% endif %}
                </table>
            </div>
            {#
            <p class="font-medium">Renouvellement de l'adhésion</p>
            <p class="mb-6 p-2 rounded-md bg-white text-black">{{ user.dateRenewal }}</p>
            
            //pour recuperer roles
            <p>{{ user.roles ? user.roles|json_encode : '' }}</p>
            #}
        </div>
    </div>
{% endblock %}